'use strict';
// ── 事件库 ────────────────────────────────────────────────────
// tier: project(绑在制项目，phase 限定阶段，null=任意阶段) / company / person / release
// cond(c) 决定能否触发，c = {p:项目, e:主创, w:作品}
// choices[].cost 正数是花钱，负数是进账；label/note/text 可以写成函数
// mood 决定用哪张氛围图（assets/scene/mood-*.webp）
const Q=(p,k,n)=>{p.quality[k]=Math.max(0,(p.quality[k]||0)+n)};
const EN=(list,n)=>list.forEach(e=>e.energy=Math.max(0,Math.min(100,e.energy+n)));
const TEAM=p=>teamOf(p);
const EVENTS=[
// ═══ 剧本开发（phase 0）═══
{id:'sc_end',tier:'project',phase:0,mood:'review',weight:10,cooldown:40,
 title:'结局留不留白',text:c=>`《${c.p.name}》的结局有两个版本。主笔坚持停在那通没接的电话上，平台顾问要一个交代得清清楚楚的结尾。`,
 choices:[{label:'留白到底',note:'故事 +6',apply:c=>{Q(c.p,'story',6);addNews('剧本定稿',`《${c.p.name}》保留了开放式结局。`)}},
  {label:'办一场三十人试读会',cost:90000,note:'导演 +7 · 故事 +2',apply:c=>{Q(c.p,'vision',7);Q(c.p,'story',2);addNews('剧本定稿',`《${c.p.name}》按试读反馈改了结局。`)}}],
 onSkip:c=>addNews('剧本',`《${c.p.name}》的结局之争没人拍板，先照原稿走。`)},
{id:'sc_side',tier:'project',phase:0,mood:'review',weight:9,cooldown:40,
 title:'原著作者要求保留支线',text:c=>`《${c.p.name}》删掉那条兄弟线能省十二场戏，作者不同意，说删了就不是这个故事了。`,
 choices:[{label:'保留支线',cost:80000,note:'故事 +5',apply:c=>{Q(c.p,'story',5);addNews('剧本',`《${c.p.name}》保住了原著支线。`)}},
  {label:'加钱买断改编自由',cost:120000,note:'导演 +8',apply:c=>{Q(c.p,'vision',8);addNews('剧本',`《${c.p.name}》买断改编权，放开手改。`)}}],
 onSkip:c=>{Q(c.p,'story',-2);addNews('剧本',`《${c.p.name}》和作者僵住了，剧本停了半周。`)}},
{id:'sc_type',tier:'project',phase:0,mood:'review',weight:9,cooldown:36,
 title:'类型定位吵起来了',text:c=>`《${c.p.name}》的策划会上分成两派：一派要在前十分钟加个钩子，一派说这片子就该冷下来。`,
 choices:[{label:'前十分钟加钩子',cost:60000,note:'故事 +7',apply:c=>{Q(c.p,'story',7);addNews('剧本',`《${c.p.name}》重写了开场。`)}},
  {label:'按导演的来',note:'导演 +5 · 核心影迷 +6',apply:c=>{Q(c.p,'vision',5);S.audiences.cinephile+=6;addNews('剧本',`《${c.p.name}》保持了原来的调子。`)}}],
 onSkip:c=>addNews('剧本',`《${c.p.name}》两派谁也没说服谁。`)},
{id:'sc_censor',tier:'project',phase:0,mood:'review',weight:7,cooldown:60,
 title:'题材踩到边界',text:c=>`《${c.p.name}》里有一段现实指涉写得很直接。留着更有劲，但备案那关不好说。`,
 choices:[{label:'大胆保留',note:'故事 +8 · 后面可能有麻烦',apply:c=>{Q(c.p,'story',8);queueChain('censor',c.p);addNews('剧本',`《${c.p.name}》保留了那段戏。`)}},
  {label:'稳妥改写',note:'故事 +3',apply:c=>{Q(c.p,'story',3);addNews('剧本',`《${c.p.name}》把那段改得含蓄了些。`)}}],
 onSkip:c=>{Q(c.p,'story',2)}},
{id:'sc_ghost',tier:'project',phase:0,mood:'review',weight:6,cooldown:70,
 title:'第三稿是枪手写的',text:c=>`编剧承认第三稿有小半是他学生代笔的。质量看不出问题，但署名这事一旦传出去就是麻烦。`,
 choices:[{label:'推倒重写这部分',cost:150000,note:'故事 +6 · 干净',apply:c=>{Q(c.p,'story',6);addNews('剧本',`《${c.p.name}》重写了代笔部分。`)}},
  {label:'给学生署联合编剧',note:'故事 +2 · 舆情 +2',apply:c=>{Q(c.p,'story',2);buzz(2);addNews('剧本',`《${c.p.name}》给年轻编剧署了名。`)}},
  {label:'当不知道',note:'25% 概率日后被曝',apply:c=>{if(Math.random()<.25){buzz(-8);S.fame=Math.max(0,S.fame-1);addNews('署名风波',`《${c.p.name}》代笔的事还是传出去了。`)}else addNews('剧本',`《${c.p.name}》的署名争议悄悄按下去了。`)}}]},
{id:'sc_real',tier:'project',phase:0,mood:'sign',weight:6,cooldown:70,cond:c=>['秘密往事','孤胆追凶','职场博弈'].includes(c.p.script.theme),
 title:'原型人物找上门',text:c=>`一个自称是《${c.p.name}》里原型的人找到公司，说故事是他的，要一笔授权费，否则就发声明。`,
 choices:[{label:'签授权，把他挂顾问',cost:200000,note:'故事 +7 · 舆情 +3',apply:c=>{Q(c.p,'story',7);buzz(3);addNews('剧本',`《${c.p.name}》和原型签了授权，人物更扎实了。`)}},
  {label:'改名改身份，撇清关系',note:'故事 -3',apply:c=>{Q(c.p,'story',-3);addNews('剧本',`《${c.p.name}》把人物改得面目全非。`)}}],
 onSkip:c=>{buzz(-3);addNews('剧本',`《${c.p.name}》没理会原型的声明，网上吵了两天。`)}},
{id:'sc_ai',tier:'project',phase:0,mood:'review',weight:5,cooldown:60,
 title:'有人交了一版机器大纲',text:c=>`策划组交上来的《${c.p.name}》分场大纲，结构工整得可疑，问下来是拿模型生成的初稿。`,
 choices:[{label:'当参考，人重写一遍',cost:70000,note:'故事 +5 · 进度 +6',apply:c=>{Q(c.p,'story',5);c.p.progress+=6;addNews('剧本',`《${c.p.name}》拿机器稿当参考，人工重写。`)}},
  {label:'直接用，省时间',note:'进度 +14 · 故事 -4',apply:c=>{c.p.progress+=14;Q(c.p,'story',-4);addNews('剧本',`《${c.p.name}》直接用了那版大纲，进度快了不少。`)}}]},
// ═══ 前期筹备（phase 1）═══
{id:'pr_budget',tier:'project',phase:1,mood:'idle',weight:10,cooldown:40,
 title:'核心场景超预算',text:c=>`《${c.p.name}》的主场景美术做了一个两层楼的实景方案，报价比计划多出十八万。`,
 choices:[{label:'砍成一层，剩下的靠镜头',note:'导演 +5',apply:c=>{Q(c.p,'vision',5);addNews('筹备',`《${c.p.name}》缩小了搭景规模。`)}},
  {label:'照方案搭',cost:180000,note:'视听 +9',apply:c=>{Q(c.p,'visual',9);addNews('筹备',`《${c.p.name}》按原方案搭了景。`)}}]},
{id:'pr_actor',tier:'project',phase:1,mood:'idle',weight:10,cooldown:40,
 title:'主演只剩十一天档期',text:c=>`主演那边压了两个组，能给《${c.p.name}》的连续档期只有十一天，超了就要断。`,
 choices:[{label:'重排通告，集中拍他的戏',cost:70000,note:'导演 +7',apply:c=>{Q(c.p,'vision',7);addNews('筹备',`《${c.p.name}》把主演的戏压到十一天里拍完。`)}},
  {label:'背影和远景用替身',note:'表演 +4 · 进度 +8',apply:c=>{Q(c.p,'performance',4);c.p.progress+=8;addNews('筹备',`《${c.p.name}》启用了替身方案。`)}}]},
{id:'pr_board',tier:'project',phase:1,mood:'idle',weight:8,cooldown:40,
 title:'那场长镜头要不要预演',text:c=>`《${c.p.name}》开场那个穿三个房间的长镜头，没预演就上，现场很可能耗掉两天。`,
 choices:[{label:'租棚做技术预演',cost:100000,note:'导演 +8',apply:c=>{Q(c.p,'vision',8);addNews('筹备',`《${c.p.name}》做了一次完整的技术预演。`)}},
  {label:'到现场随机应变',note:'导演 +4 · 拍摄时可能出事',apply:c=>{Q(c.p,'vision',4);if(Math.random()<.4)queueChain('longtake',c.p);addNews('筹备',`《${c.p.name}》决定现场解决。`)}}]},
{id:'pr_place',tier:'project',phase:1,mood:'sign',weight:8,cooldown:50,
 title:'品牌方带钱进组',text:c=>`一家饮料品牌愿意给《${c.p.name}》注资四十万，条件是片子里得有几处能看清商标的镜头。`,
 choices:[{label:'接',cost:-400000,note:'进账 40 万 · 导演 +2',apply:c=>{Q(c.p,'vision',2);queueChain('placement',c.p);addNews('筹备',`《${c.p.name}》接了品牌植入。`)}},
  {label:'婉拒',note:'导演 +4',apply:c=>{Q(c.p,'vision',4);addNews('筹备',`《${c.p.name}》回绝了植入。`)}}]},
{id:'pr_loc',tier:'project',phase:1,mood:'idle',weight:7,cooldown:45,
 title:'选好的外景地坐地起价',text:c=>`《${c.p.name}》定的那条老街，房东听说是剧组，租金一口气翻了三倍。`,
 choices:[{label:'照价租',cost:160000,note:'视听 +7',apply:c=>{Q(c.p,'visual',7);addNews('筹备',`《${c.p.name}》咬牙租下了老街。`)}},
  {label:'换到郊区的替代景',note:'视听 +2 · 进度 -6',apply:c=>{Q(c.p,'visual',2);c.p.progress=Math.max(0,c.p.progress-6);addNews('筹备',`《${c.p.name}》换了外景地，重做了勘景。`)}}]},
{id:'pr_permit',tier:'project',phase:1,mood:'review',weight:6,cooldown:55,
 title:'封路批不下来',text:c=>`那场追车戏要封的路段临着三个小区，交管那边一直没松口。`,
 choices:[{label:'改到影视基地的街景',cost:90000,note:'进度 +10 · 视听 -2',apply:c=>{c.p.progress+=10;Q(c.p,'visual',-2);addNews('筹备',`《${c.p.name}》把追车戏改到基地拍。`)}},
  {label:'等批文，先拍别的',note:'进度 -8 · 视听 +6',apply:c=>{c.p.progress=Math.max(0,c.p.progress-8);Q(c.p,'visual',6);addNews('筹备',`《${c.p.name}》等到了封路批文。`)}}]},
{id:'pr_order',tier:'project',phase:1,mood:'press',weight:6,cooldown:55,cond:()=>S.staff.filter(e=>e.role==='actor').length>=2,
 title:'两个演员争番位',text:c=>`《${c.p.name}》的海报上谁的名字在前，两边的经纪人已经各自打了三通电话。`,
 choices:[{label:'按戏份排，谁多谁前',note:'表演 +6',apply:c=>{Q(c.p,'performance',6);addNews('剧组',`《${c.p.name}》按戏份定了番位。`)}},
  {label:'做两版海报，各自发',cost:60000,note:'舆情 +3',apply:c=>{buzz(3);addNews('宣发',`《${c.p.name}》做了两版主海报。`)}},
  {label:'谁不服就换人',note:'表演 -5 · 进度 -5',apply:c=>{Q(c.p,'performance',-5);c.p.progress=Math.max(0,c.p.progress-5);addNews('剧组',`《${c.p.name}》临时换了一名演员。`)}}]},
// ═══ 正式拍摄（phase 2）═══
{id:'sh_rain',tier:'project',phase:2,mood:'rain',weight:10,cooldown:36,
 title:'雨戏等不到雨',text:c=>`《${c.p.name}》外景组连着四天拿着雨具待命，天气预报还是晴。每停一天，两百多人的盒饭照发。`,
 choices:[{label:'改成夜戏先拍别的',note:'导演 +5',apply:c=>{Q(c.p,'vision',5);addNews('片场',`《${c.p.name}》调整通告，先拍夜戏。`)}},
  {label:'叫洒水车和雨具组',cost:160000,note:'视听 +8',apply:c=>{Q(c.p,'visual',8);addNews('片场',`《${c.p.name}》人工造雨，拍完了那场戏。`)}}]},
{id:'sh_improv',tier:'project',phase:2,mood:'idle',weight:9,cooldown:36,
 title:'主演要即兴',text:c=>`主演说那段台词照本念像在背书，他想自己来。导演已经喊了停，全场在等。`,
 choices:[{label:'让他来一条',cost:30000,note:'表演 +7',apply:c=>{Q(c.p,'performance',7);addNews('片场',`《${c.p.name}》留下了那条即兴。`)}},
  {label:'按分镜走',note:'导演 +5',apply:c=>{Q(c.p,'vision',5);addNews('片场',`《${c.p.name}》还是按分镜拍完了。`)}}]},
{id:'sh_ins',tier:'project',phase:2,mood:'idle',weight:8,cooldown:40,
 title:'保险公司要加保费',text:c=>`那场从二楼翻下来的戏，保险公司看完方案要求加保，或者改设计。`,
 choices:[{label:'加保，按原方案拍',cost:140000,note:'表演 +8',apply:c=>{Q(c.p,'performance',8);addNews('片场',`《${c.p.name}》补了保费，动作戏照拍。`)}},
  {label:'改成近景剪辑',note:'视听 +5',apply:c=>{Q(c.p,'visual',5);addNews('片场',`《${c.p.name}》用剪辑规避了危险动作。`)}}]},
{id:'sh_injury',tier:'project',phase:2,mood:'hospital',weight:7,cooldown:60,
 title:'主演扭伤了',text:c=>`拍打戏时主演落地没站稳，队医说至少歇十天。他本人说还能拍。`,
 choices:[{label:'停机十天',note:'导演 +3 · 进度 -10',apply:c=>{Q(c.p,'vision',3);c.p.progress=Math.max(0,c.p.progress-10);addNews('片场',`《${c.p.name}》停机让主演养伤。`)}},
  {label:'带伤硬拍',note:'表演 +7 · 后面可能出事',apply:c=>{Q(c.p,'performance',7);queueChain('injury',c.p);addNews('片场',`《${c.p.name}》主演带伤继续拍。`)}}]},
{id:'sh_night',tier:'project',phase:2,mood:'idle',weight:8,cooldown:40,
 title:'连着第六个大夜',text:c=>`《${c.p.name}》连拍六个通宵，灯光组已经有人在换片时打瞌睡。`,
 choices:[{label:'放一天假',note:'全组体力 +12',apply:c=>{EN(TEAM(c.p),12);addNews('片场',`《${c.p.name}》剧组放了一天。`)}},
  {label:'发夜班补贴接着拍',cost:90000,note:'进度 +12 · 体力 -6',apply:c=>{c.p.progress+=12;EN(TEAM(c.p),-6);addNews('片场',`《${c.p.name}》加了夜班补贴，通告照旧。`)}}]},
{id:'sh_extra',tier:'project',phase:2,mood:'wrap',weight:7,cooldown:45,
 title:'群演把盒饭掀了',text:c=>`两百个群演等到下午三点还没开饭，领队把桌子一掀，现场停了四十分钟。视频已经有人拍了。`,
 choices:[{label:'当场补钱道歉',cost:50000,note:'舆情 +2',apply:c=>{buzz(2);addNews('片场',`《${c.p.name}》现场补了群演的钱。`)}},
  {label:'换一家群演公司',note:'进度 -6',apply:c=>{c.p.progress=Math.max(0,c.p.progress-6);addNews('片场',`《${c.p.name}》换了群演公司。`)}},
  {label:'压下去，接着拍',note:'舆情 -6',apply:c=>{buzz(-6);addNews('片场',`《${c.p.name}》的群演风波上了本地热搜。`)}}]},
{id:'sh_leak',tier:'project',phase:2,mood:'online',weight:7,cooldown:50,
 title:'剧照泄露了',text:c=>`一张没修的片场照流到网上，主演的造型被扒了个遍，评论一半说有质感一半说土。`,
 choices:[{label:'顺势放物料，把话题接住',cost:80000,note:'舆情 +5',apply:c=>{buzz(5);S.audiences[c.p.target]+=8;addNews('宣发',`《${c.p.name}》借泄露的剧照提前造了一波势。`)}},
  {label:'发函要求删除',note:'视听 +3 · 舆情 -2',apply:c=>{buzz(-2);Q(c.p,'visual',3);addNews('宣发',`《${c.p.name}》要求下架了流出的剧照。`)}}]},
{id:'sh_truck',tier:'project',phase:2,mood:'rain',weight:6,cooldown:55,
 title:'器材车在高速上追尾',text:c=>`没伤到人，但两台摄影机和一套灯要送修，最快也要五天。`,
 choices:[{label:'租一套顶上',cost:130000,note:'进度不受影响',apply:c=>addNews('片场',`《${c.p.name}》紧急租了一套设备。`)},
  {label:'等修，先拍小场景',note:'进度 -9 · 视听 +4',apply:c=>{c.p.progress=Math.max(0,c.p.progress-9);Q(c.p,'visual',4);addNews('片场',`《${c.p.name}》调整通告，先拍室内。`)}}]},
// ═══ 后期制作（phase 3）═══
{id:'po_shot',tier:'project',phase:3,mood:'idle',weight:10,cooldown:36,
 title:'缺一个空镜',text:c=>`《${c.p.name}》剪到最后那场，情绪落不下来——少一个能让观众喘口气的镜头，素材里翻不出来。`,
 choices:[{label:'补拍一天',cost:120000,note:'视听 +7',apply:c=>{Q(c.p,'visual',7);addNews('后期',`《${c.p.name}》补拍了结尾的空镜。`)}},
  {label:'用现有素材重构结尾',note:'故事 +4',apply:c=>{Q(c.p,'story',4);addNews('后期',`《${c.p.name}》重剪了结尾。`)}}]},
{id:'po_test',tier:'project',phase:3,mood:'review',weight:9,cooldown:36,
 title:'试映意见劈成两半',text:c=>`三十人试映，年轻观众说中段太慢，影迷说那正是全片最好的十分钟。`,
 choices:[{label:'压掉十分钟',cost:80000,note:'视听 +7 · 年轻观众 +10',apply:c=>{Q(c.p,'visual',7);S.audiences.youth+=10;addNews('后期',`《${c.p.name}》剪短了中段。`)}},
  {label:'保留人物的停顿',note:'故事 +5 · 核心影迷 +10',apply:c=>{Q(c.p,'story',5);S.audiences.cinephile+=10;addNews('后期',`《${c.p.name}》保留了原来的节奏。`)}}]},
{id:'po_music',tier:'project',phase:3,mood:'idle',weight:8,cooldown:45,
 title:'有位音乐人愿意接主题曲',text:c=>`价格是市价的一半，条件是这周之内定，因为他下周进棚做别的。`,
 choices:[{label:'签',cost:150000,note:'表演 +8 · 舆情 +3',apply:c=>{Q(c.p,'performance',8);buzz(3);addNews('后期',`《${c.p.name}》定下了主题曲。`)}},
  {label:'用原创配乐',note:'导演 +5',apply:c=>{Q(c.p,'vision',5);addNews('后期',`《${c.p.name}》沿用了作曲的原创配乐。`)}}]},
{id:'po_vfx',tier:'project',phase:3,mood:'idle',weight:7,cooldown:45,cond:c=>c.p.scale!=='web',
 title:'特效公司拖稿',text:c=>`四十个镜头只交了十二个，对方说主力团队被另一个组抽走了。`,
 choices:[{label:'加钱插队',cost:200000,note:'视听 +8',apply:c=>{Q(c.p,'visual',8);addNews('后期',`《${c.p.name}》加钱把特效排期抢了回来。`)}},
  {label:'砍掉十个镜头',note:'视听 -4 · 进度 +10',apply:c=>{Q(c.p,'visual',-4);c.p.progress+=10;addNews('后期',`《${c.p.name}》删减了特效镜头。`)}},
  {label:'换一家小公司做',cost:80000,note:'一半概率更糟',apply:c=>{if(Math.random()<.5){Q(c.p,'visual',5);addNews('后期',`《${c.p.name}》换的新公司交得又快又好。`)}else{Q(c.p,'visual',-6);addNews('后期',`《${c.p.name}》换的公司质量还不如原来。`)}}}]},
{id:'po_title',tier:'project',phase:3,mood:'sign',weight:7,cooldown:50,
 title:'发行建议改片名',text:c=>`发行那边说《${c.p.name}》这个名字在售票软件上没人会点进来，给了三个更直白的备选。`,
 choices:[{label:'改成更好卖的名字',note:'大众市场 +14 · 故事 -3',apply:c=>{S.audiences.mass+=14;Q(c.p,'story',-3);addNews('宣发',`《${c.p.name}》换了个更商业的片名。`)}},
  {label:'不改',note:'导演 +5 · 核心影迷 +8',apply:c=>{Q(c.p,'vision',5);S.audiences.cinephile+=8;addNews('宣发',`《${c.p.name}》坚持了原片名。`)}}]},
{id:'po_dub',tier:'project',phase:3,mood:'idle',weight:6,cooldown:50,
 title:'现场声全废了',text:c=>`那三天的同期声底噪太大，要么全部重配，要么留着这股毛边。`,
 choices:[{label:'进棚全部重配',cost:110000,note:'表演 +6',apply:c=>{Q(c.p,'performance',6);addNews('后期',`《${c.p.name}》重配了三天的戏。`)}},
  {label:'留着现场感',note:'视听 -3 · 故事 +3',apply:c=>{Q(c.p,'visual',-3);Q(c.p,'story',3);addNews('后期',`《${c.p.name}》保留了粗糙的现场声。`)}}]},
// ═══ 制作期任意阶段 ═══
{id:'an_press',tier:'project',phase:null,mood:'press',weight:8,cooldown:40,
 title:'媒体想探班',text:c=>`四家媒体想进《${c.p.name}》的组，探班稿能换一波曝光，但那天的通告肯定要拖。`,
 choices:[{label:'安排半天探班',cost:40000,note:'舆情 +4 · 进度 -4',apply:c=>{buzz(4);c.p.progress=Math.max(0,c.p.progress-4);addNews('宣发',`《${c.p.name}》开放了半天探班。`)}},
  {label:'闭组，一个都不放',note:'进度 +4',apply:c=>{c.p.progress+=4;addNews('宣发',`《${c.p.name}》拒绝了所有探班。`)}}]},
{id:'an_cut',tier:'project',phase:null,mood:'review',weight:7,cooldown:45,
 title:'投资方要看粗剪',text:c=>`《${c.p.name}》还没剪完就要看，看完难免有意见。但拒绝的话，下一部的钱就不好张嘴了。`,
 choices:[{label:'放给他们看',note:'导演 +3 · 一半概率被提意见',apply:c=>{Q(c.p,'vision',3);if(Math.random()<.5){Q(c.p,'story',-4);addNews('投资方',`投资方看完粗剪提了七条意见，剧组照改了三条。`)}else addNews('投资方',`投资方看完粗剪，没多说什么。`)}},
  {label:'推到成片再说',note:'关系变差',apply:c=>{S.flags.investorCold=true;addNews('投资方',`公司拒绝了粗剪送审，对方在电话里沉默了几秒。`)}}]},
{id:'an_fight',tier:'project',phase:null,mood:'idle',weight:7,cooldown:45,cond:c=>TEAM(c.p).length>=3,
 title:'导演和摄影吵起来了',text:c=>`为了一个机位，两个人在监视器前吵了二十分钟，全组站着等。`,
 choices:[{label:'制片出面压下来',note:'导演 +5',apply:c=>{Q(c.p,'vision',5);addNews('片场',`《${c.p.name}》的争执被制片人压了下去。`)}},
  {label:'两个机位都拍',cost:70000,note:'视听 +7',apply:c=>{Q(c.p,'visual',7);addNews('片场',`《${c.p.name}》两个方案各拍了一条。`)}},
  {label:'让他们自己解决',note:'一半概率拍出好东西',apply:c=>{if(Math.random()<.5){Q(c.p,'visual',6);Q(c.p,'vision',3);addNews('片场',`《${c.p.name}》吵完之后，两个人给出了更好的方案。`)}else{EN(TEAM(c.p),-8);addNews('片场',`《${c.p.name}》的争执拖到了后半夜。`)}}}]},
{id:'an_early',tier:'project',phase:null,mood:'wrap',weight:6,cooldown:50,cond:c=>c.p.progress>40,
 title:'可以提前杀青',text:c=>`按现在的进度，《${c.p.name}》砍掉两场过场戏就能提前一周杀青，省下一周的组盘。`,
 choices:[{label:'砍戏，提前收工',note:'进度 +16 · 故事 -4',apply:c=>{c.p.progress+=16;Q(c.p,'story',-4);addNews('片场',`《${c.p.name}》提前一周杀青。`)}},
  {label:'该拍的都拍完',note:'全组体力 -4 · 故事 +4',apply:c=>{EN(TEAM(c.p),-4);Q(c.p,'story',4);addNews('片场',`《${c.p.name}》按原计划拍完了所有戏。`)}}]},
// ═══ 公司事件 ═══
{id:'co_tax',tier:'company',mood:'review',weight:7,cooldown:80,cond:()=>S.works.length>=2,
 title:'税务来查账',text:()=>`税务部门抽查影视公司，公司三年的账要在两周内整理出来。`,
 choices:[{label:'请会计所全面配合',cost:150000,note:'干净收场',apply:()=>addNews('公司',`税务检查顺利结束，没查出问题。`)},
  {label:'自己应付',note:'四成概率补税',apply:()=>{if(Math.random()<.4){const f=Math.round(300000+S.works.length*40000);S.money-=f;buzz(-4);addNews('公司',`税务检查要求补缴 ${money(f)}。`)}else addNews('公司',`税务检查过去了，虚惊一场。`)}}]},
{id:'co_policy',tier:'company',mood:'review',weight:8,cooldown:60,
 title:'平台改了采购口径',text:()=>`几家平台同时下调了网络电影的分账单价，说是要把钱留给头部。`,
 choices:[{label:'跟着调整片单',note:'大众市场 +12',apply:()=>{S.flags.policyShift=true;S.audiences.mass+=12;addNews('行业',`公司调整了片单结构，往中高成本靠。`)}},
  {label:'不动，继续做量',cost:-200000,note:'进账 20 万 · 舆情 -2',apply:()=>{buzz(-2);addNews('行业',`公司继续按原计划做网络电影。`)}}]},
{id:'co_investor',tier:'company',mood:'sign',weight:8,cooldown:70,cond:()=>S.fame>=5,
 title:'有人想投钱进来',text:()=>`一家做地产起家的公司想投两千万，要一个片单的决策席位。`,
 choices:[{label:'接受投资',cost:-20000000,note:'进账 2000 万 · 以后选题受干预',apply:()=>{S.flags.outsideMoney=true;addNews('公司',`公司引入外部投资两千万，对方进了决策会。`)}},
  {label:'只要钱不要席位，谈崩了',note:'声望 +2',apply:()=>{S.prestige+=2;addNews('公司',`公司拒绝了带席位的投资。`)}}]},
{id:'co_rent',tier:'company',mood:'idle',weight:7,cooldown:60,
 title:'场地要涨租',text:()=>`房东说周边都涨了，续约租金上浮两成，不签就腾地方。`,
 choices:[{label:'签',note:'认了',apply:()=>{S.flags.rentUp=true;addNews('公司',`公司续了租，月固定支出上涨。`)}},
  {label:'一次性付三年，谈回原价',cost:1200000,note:'省长期成本',apply:()=>addNews('公司',`公司一次性付了三年租金，锁住了原价。`)}]},
{id:'co_theft',tier:'company',mood:'idle',weight:5,cooldown:90,cond:()=>S.studio>=1,
 title:'库房被撬了',text:()=>`周末库房进了人，丢了两台机器和一批镜头，监控只拍到背影。`,
 choices:[{label:'报保险，补设备',cost:180000,note:'损失可控',apply:()=>addNews('公司',`设备已补齐，保险赔了一部分。`)},
  {label:'先凑合用',note:'在制项目视听 -3',apply:()=>{S.projects.forEach(p=>Q(p,'visual',-3));addNews('公司',`库房失窃后，剧组暂时用租来的旧设备。`)}}]},
{id:'co_fest',tier:'company',mood:'press',weight:8,cooldown:50,cond:()=>S.works.some(w=>w.score>=7.4),
 title:'电影节报名截止了',text:()=>`报名费加物料制作十二万。入围能换一批影评人的注意力，落选就是白花。`,
 choices:[{label:'报名',cost:120000,note:'四成半概率入围',apply:()=>{if(Math.random()<.45){S.prestige+=6;buzz(6);S.audiences.cinephile+=25;addNews('电影节',`公司作品入围主竞赛，影迷群体涨了一批。`)}else addNews('电影节',`公司作品没能入围。`)}},
  {label:'不报',note:'省钱',apply:()=>addNews('电影节',`公司今年没报节展。`)}]},
{id:'co_poach_all',tier:'company',mood:'press',weight:5,cooldown:90,cond:()=>S.staff.length>=8,
 title:'有人想端走整个团队',text:()=>`一家新成立的公司找到三名主创，开的价比现在高四成，说要把整个班底搬过去。`,
 choices:[{label:'集体涨薪一成，把人按住',note:'全员月薪 +10%',apply:()=>{S.staff.forEach(e=>e.salary=Math.round(e.salary*1.1));addNews('公司',`公司给全员涨了一成薪，人留住了。`)}},
  {label:'挑两个核心单独谈',cost:600000,note:'留住核心，其余可能走',apply:()=>{if(Math.random()<.5&&S.staff.length>4){const e=S.staff[rnd(3,S.staff.length-1)];leaveStaff(e);addNews('人员流失',`${e.name}还是走了。`)}else addNews('公司',`核心主创留了下来。`)}},
  {label:'随便走',note:'走两个人',apply:()=>{for(let i=0;i<2;i++){if(S.staff.length<=3)break;const e=S.staff[rnd(0,S.staff.length-1)];leaveStaff(e);addNews('人员流失',`${e.name}离开了公司。`)}buzz(-3)}}]},
{id:'co_sub',tier:'company',mood:'sign',weight:7,cooldown:60,
 title:'专项补贴开始申报',text:()=>`本地影视扶持资金开始申报，材料要报三年的完税和备案记录，中签的拿六十万。`,
 choices:[{label:'认真报',cost:30000,note:'五成半概率拿到 60 万',apply:()=>{if(Math.random()<.55){S.money+=600000;addNews('公司',`公司拿到六十万影视扶持资金。`)}else addNews('公司',`扶持资金申报没通过。`)}},
  {label:'太麻烦，不报',note:'',apply:()=>addNews('公司',`公司放弃了这次申报。`)}]},
{id:'co_short',tier:'company',mood:'online',weight:7,cooldown:55,cond:()=>S.works.length>=3,
 title:'短视频公司找上门',text:()=>`对方想买公司片库的二创授权，一年三十万，条件是随便他们剪。`,
 choices:[{label:'授权',cost:-300000,note:'进账 30 万 · 舆情 +4',apply:()=>{S.flags.clipDeal=true;buzz(4);addNews('公司',`公司把片库二创权授了出去。`)}},
  {label:'不授',note:'',apply:()=>addNews('公司',`公司拒绝了二创授权。`)}]},
{id:'co_work',tier:'company',mood:'review',weight:7,cooldown:60,cond:()=>S.staff.length>=6,
 title:'办个内部剧本工坊',text:()=>`让编剧带着年轻人写三个月，不一定出得来东西，但人会长。`,
 choices:[{label:'办',cost:250000,note:'两名主创能力提升',apply:()=>{const pool=[...S.staff].sort(()=>Math.random()-.5).slice(0,2);pool.forEach(e=>{Object.keys(e.stats).forEach(k=>e.stats[k]+=rnd(2,5))});addNews('公司',`剧本工坊结束，${pool.map(e=>e.name).join('、')}的本事见长。`)}},
  {label:'先忙片子',note:'',apply:()=>addNews('公司',`剧本工坊的事被搁置了。`)}]},
{id:'co_bank',tier:'company',mood:'sign',weight:9,cooldown:40,cond:()=>S.money<1500000,
 title:'银行来推销贷款',text:()=>`公司账上不宽裕的消息传得很快。对方开的条件是三百万，两年内还清。`,
 choices:[{label:'借三百万',cost:-3000000,note:'两年内每月还 14.5 万',apply:()=>{S.debt=(S.debt||0)+3480000;S.debtPay=145000;addNews('公司',`公司借入三百万周转资金，两年还清。`)}},
  {label:'不借',note:'',apply:()=>addNews('公司',`公司谢绝了贷款。`)}]},
{id:'co_trash',tier:'company',mood:'online',weight:14,cooldown:50,cond:()=>(S.flags.trashStreak||0)>=2,
 title:'公司被贴上了标签',text:()=>`连着两部片子扑了。有篇行业稿把公司点名写成"批量生产烂片"的典型，转得到处都是。`,
 choices:[{label:'停一停，下一部只做小成本',cost:0,note:'舆情 +4 · 下部片更稳',apply:()=>{buzz(4);S.flags.trashStreak=0;S.flags.cautious=true;addNews('公司','公司公开表示要放慢节奏。')}},
  {label:'花钱压热搜',cost:250000,note:'舆情 +6 · 治标',apply:()=>{buzz(6);S.flags.trashStreak=0;addNews('公关','公司压下了那波讨论，但片子还是那些片子。')}},
  {label:'硬顶：下一部加大投入',cost:0,note:'舆情 -5 · 再扑一部更难看',apply:()=>{buzz(-5);addNews('公司','公司回应说下一部会证明自己。')}}],
 onSkip:()=>{buzz(-6);S.flags.trashStreak=0;addNews('公司','没人出来说话，"烂片厂"的说法就这么留下了。')}},
{id:'co_rumor',tier:'company',mood:'online',weight:6,cooldown:70,cond:()=>S.fame>=8,
 title:'传闻说公司要被收购',text:()=>`一篇没署名的行业稿把公司写成待价而沽，合作方开始打听。`,
 choices:[{label:'发声明否认',cost:20000,note:'舆情 +3',apply:()=>{buzz(3);addNews('公司',`公司发声明否认收购传闻。`)}},
  {label:'不回应，让它传',note:'舆情 -3 · 可能有人真来谈',apply:()=>{buzz(-3);if(Math.random()<.3){S.money+=1500000;addNews('公司',`传闻招来了真金白银：有人先付了一笔独家洽谈金。`)}else addNews('公司',`收购传闻自己淡了。`)}}]},
// ═══ 人物事件 ═══
{id:'pe_block',tier:'person',mood:'idle',weight:9,cooldown:40,cond:c=>c.e.level>=2,
 title:'创作瓶颈',text:c=>`${c.e.name}最近交上来的东西都在及格线上下，本人也知道，说写不动了。`,
 choices:[{label:'放两个月假',note:'体力回满，能力略增',apply:c=>{c.e.energy=100;c.e.status='rest';Object.keys(c.e.stats).forEach(k=>c.e.stats[k]+=rnd(1,3));addNews('团队',`${c.e.name}休整一段时间，状态回来了。`)}},
  {label:'送去跟一个大组学',cost:120000,note:'能力明显提升',apply:c=>{Object.keys(c.e.stats).forEach(k=>c.e.stats[k]+=rnd(3,6));addNews('团队',`${c.e.name}跟了一个大组回来，眼界不一样了。`)}},
  {label:'压任务，逼一逼',note:'一半突破，一半掉状态',apply:c=>{if(Math.random()<.5){Object.keys(c.e.stats).forEach(k=>c.e.stats[k]+=rnd(2,5));addNews('团队',`${c.e.name}硬扛过来了。`)}else{c.e.energy=Math.max(0,c.e.energy-30);addNews('团队',`${c.e.name}状态更差了。`)}}}]},
{id:'pe_master',tier:'person',mood:'idle',weight:7,cooldown:50,cond:c=>c.e.level>=3&&S.staff.length>=5,
 title:'带个徒弟',text:c=>`${c.e.name}想带公司里最年轻的那个，条件是这半年少接一部戏。`,
 choices:[{label:'同意',note:'年轻主创能力提升',apply:c=>{const y=S.staff.filter(e=>e.id!==c.e.id).sort((a,b)=>a.level-b.level)[0];if(y)Object.keys(y.stats).forEach(k=>y.stats[k]+=rnd(4,8));c.e.energy=Math.max(0,c.e.energy-10);addNews('团队',`${c.e.name}带起了徒弟。`)}},
  {label:'现在忙，以后再说',note:'',apply:c=>addNews('团队',`${c.e.name}带徒弟的事往后推了。`)}]},
{id:'pe_gossip',tier:'person',mood:'online',weight:7,cooldown:55,cond:c=>c.e.role==='actor'||c.e.star,
 title:'绯闻上了热搜',text:c=>`${c.e.name}和某位合作过的演员被拍到一起吃饭，词条挂了六个小时。`,
 choices:[{label:'公关按下去',cost:120000,note:'舆情 +1',apply:c=>{buzz(1);addNews('公关',`${c.e.name}的绯闻被压了下去。`)}},
  {label:'顺势炒一波',note:'舆情 +6 · 声望 -2',apply:c=>{buzz(6);S.prestige=Math.max(0,S.prestige-2);S.audiences.women+=15;addNews('公关',`${c.e.name}的话题被顺势做成了物料。`)}},
  {label:'不管',note:'舆情 -2',apply:c=>{buzz(-2);addNews('公关',`公司没管${c.e.name}的绯闻，两天后自己淡了。`)}}]},
{id:'pe_direct',tier:'person',mood:'review',weight:6,cooldown:60,cond:c=>c.e.role!=='director'&&c.e.level>=3,
 title:'他想当导演',text:c=>`${c.e.name}写了一个自己的本子，想要一部低成本片的机会。`,
 choices:[{label:'给他一部网络电影',cost:300000,note:'转岗为导演',apply:c=>{c.e.role='director';c.e.stats.vision+=rnd(8,14);c.e.face=pickFace('director',!!c.e.star);addNews('团队',`${c.e.name}转做导演，公司给了一部小片。`)}},
  {label:'再等等',note:'他会记着这事',apply:c=>{c.e.grudge=(c.e.grudge||0)+1;addNews('团队',`${c.e.name}的导演梦被搁置了。`)}}]},
{id:'pe_lead',tier:'person',mood:'press',weight:6,cooldown:55,cond:c=>c.e.role==='actor'&&c.e.level>=2,
 title:'他想演主角',text:c=>`${c.e.name}演了三部配角，这次直接说：下一部要么给我主角，要么我出去接戏。`,
 choices:[{label:'下一部给他',note:'表演提升',apply:c=>{c.e.stats.performance+=rnd(5,9);c.e.promised=true;addNews('团队',`公司答应下一部让${c.e.name}挑大梁。`)}},
  {label:'按能力说话',note:'他可能走',apply:c=>{if(Math.random()<.35&&S.staff.length>3){leaveStaff(c.e);addNews('人员流失',`${c.e.name}出去接戏，没再回来。`)}else addNews('团队',`${c.e.name}接受了现实。`)}}]},
{id:'pe_family',tier:'person',mood:'idle',weight:7,cooldown:45,
 title:'家里出事要请假',text:c=>`${c.e.name}家里有急事，要走两个月。手上的活要么分出去，要么等他。`,
 choices:[{label:'准假，活分给别人',note:'在制项目进度 -6',apply:c=>{c.e.status='rest';c.e.energy=60;S.projects.forEach(p=>{p.progress=Math.max(0,p.progress-6)});addNews('团队',`${c.e.name}请了两个月假。`)}},
  {label:'给一笔钱，请他尽快回来',cost:80000,note:'进度不受影响 · 舆情 +2',apply:c=>{buzz(2);addNews('团队',`公司给${c.e.name}安排了后勤，他很快回了组。`)}},
  {label:'不批',note:'舆情 -5 · 他会记恨',apply:c=>{buzz(-5);c.e.grudge=(c.e.grudge||0)+2;addNews('团队',`${c.e.name}的假没批下来。`)}}]},
{id:'pe_dinner',tier:'person',mood:'sign',weight:7,cooldown:50,cond:c=>c.e.level>=2,
 title:'对手约他吃饭',text:c=>`${c.e.name}被一家竞争公司约了饭。他自己主动说了这事，等于在等公司表态。`,
 choices:[{label:'当场涨薪 15%',note:'合约续两年',apply:c=>{c.e.salary=Math.round(c.e.salary*1.15);c.e.contract={until:stamp()+24,share:c.e.contract?.share||0};addNews('团队',`公司给${c.e.name}涨了薪。`)}},
  {label:'口头认可，不加钱',note:'一半概率他会动摇',apply:c=>{if(Math.random()<.5){c.e.grudge=(c.e.grudge||0)+1;addNews('团队',`${c.e.name}没说什么，但饭还是去吃了。`)}else addNews('团队',`${c.e.name}回绝了对手的邀约。`)}}]},
{id:'pe_burn',tier:'person',mood:'hospital',weight:7,cooldown:40,cond:c=>c.e.energy<35,
 title:'他撑不住了',text:c=>`${c.e.name}连着几个月没歇，今天在剪辑房睡着了，叫了三次才醒。`,
 choices:[{label:'强制休整一个月',note:'体力恢复',apply:c=>{c.e.status='rest';c.e.energy=Math.max(c.e.energy,70);addNews('团队',`${c.e.name}被强制休整。`)}},
  {label:'给加班费接着干',cost:60000,note:'体力 +15 · 舆情 -3',apply:c=>{c.e.energy=Math.min(100,c.e.energy+15);buzz(-3);addNews('团队',`${c.e.name}拿了加班费，继续跟组。`)}}]},
{id:'pe_show',tier:'person',mood:'press',weight:6,cooldown:55,cond:c=>c.e.star,
 title:'综艺邀约',text:c=>`一档热门综艺想请${c.e.name}录四期，钱不少，但接下来两个月他基本进不了组。`,
 choices:[{label:'接',cost:-500000,note:'进账 50 万 · 舆情 +5 · 两个月不可用',apply:c=>{buzz(5);c.e.status='rest';c.e.energy=100;addNews('团队',`${c.e.name}去录综艺了。`)}},
  {label:'推掉',note:'表演提升',apply:c=>{c.e.stats.performance+=rnd(2,4);addNews('团队',`${c.e.name}推掉了综艺。`)}}]},
// ═══ 上映期事件 ═══
{id:'re_pirate',tier:'release',mood:'online',weight:8,cooldown:40,cond:c=>c.w.active&&c.w.weeks<=4,
 title:'高清盗版流出',text:c=>`《${c.w.name}》上映第${c.w.weeks+1}周，一个清晰度不低的版本在网盘里传开了。`,
 choices:[{label:'全网发函下架',cost:150000,note:'止损',apply:c=>{addNews('维权',`《${c.w.name}》的盗版资源被大批下架。`)}},
  {label:'不追，省下这笔钱',note:'后续回款 -15%',apply:c=>{c.w.potential*=.85;buzz(-2);addNews('维权',`《${c.w.name}》没有追盗版，长尾受了影响。`)}}]},
{id:'re_critic',tier:'release',mood:'online',weight:9,cooldown:36,
 title:'一篇长评把片子拆开了',text:c=>`一位有分量的影评人写了六千字谈《${c.w.name}》，夸的部分很准，骂的部分更准。`,
 choices:[{label:'转发，认下批评',note:'舆情 +5 · 声望 +2',apply:c=>{buzz(5);S.prestige+=2;addNews('口碑',`公司转发了那篇长评，态度赢了一波好感。`)}},
  {label:'找人写文章回击',cost:60000,note:'四成概率反噬',apply:c=>{if(Math.random()<.4){buzz(-8);addNews('口碑',`回击文章被扒出是买的，反而更难看。`)}else{buzz(3);addNews('口碑',`回击文章把风向扳了回来。`)}}},
  {label:'不接话',note:'',apply:c=>addNews('口碑',`公司没有回应那篇长评。`)}]},
{id:'re_clip',tier:'release',mood:'online',weight:8,cooldown:40,cond:c=>c.w.score>=6.5,
 title:'一条二创突然爆了',text:c=>`有人把《${c.w.name}》里三分钟的对手戏剪成短视频，一夜之间转了几十万。`,
 choices:[{label:'官方下场，追加投放',cost:180000,note:'商业潜力 +20% · 舆情 +6',apply:c=>{c.w.potential*=1.2;buzz(6);S.audiences[c.w.target]+=20;addNews('宣发',`《${c.w.name}》借二创又火了一轮。`)}},
  {label:'让它自己长',note:'商业潜力 +8% · 舆情 +3',apply:c=>{c.w.potential*=1.08;buzz(3);addNews('宣发',`《${c.w.name}》的二创热度自然发酵。`)}}]},
{id:'re_road',tier:'release',mood:'press',weight:7,cooldown:45,cond:c=>c.w.deal==='theater'&&c.w.active,
 title:'路演上说错了话',text:c=>`《${c.w.name}》路演现场，主演被问到某个社会话题，答得不太妥当，视频在传。`,
 choices:[{label:'当晚发道歉并说明',cost:40000,note:'止住',apply:c=>{buzz(-2);addNews('公关',`《${c.w.name}》剧组当晚做了说明。`)}},
  {label:'切掉后续路演',note:'商业潜力 -10%',apply:c=>{c.w.potential*=.9;addNews('公关',`《${c.w.name}》取消了剩下的路演场次。`)}},
  {label:'硬撑，照常跑',note:'四成概率越描越黑',apply:c=>{if(Math.random()<.4){buzz(-9);c.w.potential*=.88;addNews('公关',`《${c.w.name}》的争议越滚越大。`)}else{buzz(2);addNews('公关',`《${c.w.name}》的路演风波过去了。`)}}}]},
{id:'re_pull',tier:'release',mood:'sign',weight:6,cooldown:50,cond:c=>c.w.active&&c.w.weeks<=2,
 title:'同档对手撤了',text:c=>`原本同档的一部大片临时撤档，《${c.w.name}》这周的排片空间一下松了。`,
 choices:[{label:'加投一轮，抢排片',cost:200000,note:'商业潜力 +25%',apply:c=>{c.w.potential*=1.25;addNews('发行',`《${c.w.name}》趁对手撤档追加了投放。`)}},
  {label:'按原计划走',note:'商业潜力 +8%',apply:c=>{c.w.potential*=1.08;addNews('发行',`《${c.w.name}》吃到了一点档期红利。`)}}]},
{id:'re_ticket',tier:'release',mood:'sign',weight:7,cooldown:45,cond:c=>c.w.deal==='theater'&&c.w.active&&c.w.weeks<=2,
 title:'要不要跟票补',text:c=>`同档两部都在做九块九，《${c.w.name}》不跟的话，首周上座率会难看。`,
 choices:[{label:'跟',cost:260000,note:'商业潜力 +22%',apply:c=>{c.w.potential*=1.22;addNews('发行',`《${c.w.name}》跟进了票补。`)}},
  {label:'不跟，赌口碑',note:'评分高则后程发力',apply:c=>{if(c.w.score>=7.3){c.w.decay=Math.min(.95,c.w.decay+.05);addNews('发行',`《${c.w.name}》没做票补，靠口碑走了长线。`)}else{c.w.potential*=.88;addNews('发行',`《${c.w.name}》没跟票补，首周吃了亏。`)}}}]},
{id:'re_seq',tier:'release',mood:'sign',weight:7,cooldown:50,cond:c=>c.w.score>=7.5,
 title:'平台问续集',text:c=>`《${c.w.name}》的数据不错，平台问有没有续集计划，愿意先付一笔开发金。`,
 choices:[{label:'签开发金',cost:-800000,note:'进账 80 万 · IP疲劳 +10',apply:c=>{const ip=S.ips.find(x=>x.id===c.w.ipId);if(ip)ip.fatigue=Math.min(100,ip.fatigue+10);addNews('IP',`公司拿了《${c.w.name}》的续集开发金。`)}},
  {label:'先不接，想清楚再说',note:'IP知名度 +4',apply:c=>{const ip=S.ips.find(x=>x.id===c.w.ipId);if(ip)ip.recognition=Math.min(100,ip.recognition+4);addNews('IP',`公司没急着答应续集。`)}}]},
{id:'re_report',tier:'release',mood:'online',weight:5,cooldown:60,cond:c=>c.w.active,
 title:'有人举报了片子',text:c=>`《${c.w.name}》里一处情节被投诉价值导向有问题，相关部门要求说明情况。`,
 choices:[{label:'提交说明材料',cost:50000,note:'八成过去',apply:c=>{if(Math.random()<.8)addNews('审查',`《${c.w.name}》的投诉说明获得认可。`);else{c.w.potential*=.85;buzz(-4);addNews('审查',`《${c.w.name}》被要求调整宣传口径。`)}}},
  {label:'主动删改两处再上',note:'商业潜力 -8% · 舆情 +2',apply:c=>{c.w.potential*=.92;buzz(2);addNews('审查',`《${c.w.name}》主动做了删改。`)}}]},
{id:'re_award',tier:'release',mood:'press',weight:6,cooldown:60,cond:c=>c.w.score>=8,
 title:'要不要做冲奖运作',text:c=>`《${c.w.name}》的评分够得着奖，但评奖季要跑活动、办展映、请评委看片。`,
 choices:[{label:'做，全套',cost:400000,note:'获奖概率明显提高',apply:c=>{S.flags.awardPush=true;S.prestige+=3;addNews('评奖',`公司为《${c.w.name}》启动了评奖季运作。`)}},
  {label:'不做，片子说话',note:'声望 +1',apply:c=>{S.prestige+=1;addNews('评奖',`公司没有为《${c.w.name}》做评奖运作。`)}}]}
];
// ── 只进消息栏、不弹窗的氛围新闻 ──
const FLAVOR=[
'院线上周整体票房环比下跌一成，从业者在群里互相打气。',
'一家老牌制片公司的摄影棚挂牌出租，据说撑不住了。',
'某平台上线了分账新规，把有效播放的门槛又提了十秒。',
'行业协会公布去年备案数：比前年少了六百多部。',
'一位拍了三十年电影的老摄影去世，业内发了一天悼念。',
'短视频平台开始限制电影解说号，一批账号被封。',
'今年横店的开机量回暖，群演的日薪涨了二十块。',
'某新人导演的处女作卖出了一千万，全行业都在打听他是谁。',
'两家发行公司合并，行业里少了一个竞价方。',
'海外片商来了一批，在酒店包了三层看片。',
'一部上映十年的老片重映，票房居然进了周榜前五。',
'某明星工作室注销，媒体猜了三天。',
'影院开始卖联名饮料杯，单杯利润比电影票还高。',
'编剧维权群又转了一份拖欠稿酬的名单。',
'一批影视基地推出免场租政策，条件是片尾挂名。',
'换脸补拍被写进了几家公司的制作流程。',
'今年暑期档定档的片子已经有十一部，业内说要挤破头。',
'某卫视重启了电视电影招标，价格比五年前还低。',
'一家做了八年宣发的公司改行做直播带货。',
'电影资料馆的修复版专场票在十秒内卖光。',
'剧集平台把单集时长压到了二十八分钟。',
'一个不知名的县城影院成了周末的打卡点，因为便宜。',
'行业里开始流行先剪短视频再拍正片的说法。',
'某导演在采访里说现在没人敢拍成年人的故事，被转了一万次。',
'保险公司推出了剧组专项险，保费按拍摄天数算。',
'一批演员开始自己写本子，说等不到好角色。',
'今年金幕奖的报名费涨了，小公司在论坛上骂了一片。',
'观众调研显示，看预告片决定买不买票的人超过了六成。',
'几家影院因为空调坏了上了本地新闻。',
'有人统计了近三年的续集片，平均评分比首作低 0.7。'
];
